package ai

import (
	"github.com/user/poblation/internal/entities"
)

// DefenseResult stores the outcome of a defense mechanism activation.
type DefenseResult struct {
	// Mechanism is which defense activated.
	Mechanism entities.DefenseMechanismType `json:"mechanism"`
	// DampenFactor scales down emotional intensity (0.0 = full block, 1.0 = no effect).
	DampenFactor float32 `json:"dampen_factor"`
	// ThoughtOverride is a replacement thought generated by the defense.
	ThoughtOverride string `json:"thought_override"`
	// Activated marks whether the defense actually fired.
	Activated bool `json:"activated"`
}

// CheckDefenseMechanism evaluates whether a Poble's defense mechanism activates
// before an emotional event is processed. High-intensity events trigger defenses.
func CheckDefenseMechanism(poble *entities.Poble, eventSeverity float32) DefenseResult {
	if poble == nil {
		return DefenseResult{Activated: false}
	}

	defense := poble.Defense
	if eventSeverity < defense.Threshold {
		return DefenseResult{Activated: false}
	}

	// Primary fires first. If the event overwhelms even strength, secondary kicks in.
	mechanism := defense.Primary
	dampen := defenseEffectiveness(defense.Primary, defense.Strength, eventSeverity)
	if dampen > 0.85 && eventSeverity > 80 {
		mechanism = defense.Secondary
		dampen = defenseEffectiveness(defense.Secondary, defense.Strength*0.7, eventSeverity)
	}

	thought := defenseThought(mechanism)
	return DefenseResult{
		Mechanism:       mechanism,
		DampenFactor:    dampen,
		ThoughtOverride: thought,
		Activated:       true,
	}
}

func defenseEffectiveness(mechanism entities.DefenseMechanismType, strength, severity float32) float32 {
	ratio := strength / maxFloat32(severity, 1)
	switch mechanism {
	case entities.DefenseDenial:
		return clampUnit(1.0 - ratio*0.7)
	case entities.DefenseRepression:
		return clampUnit(1.0 - ratio*0.8)
	case entities.DefenseHumor:
		return clampUnit(1.0 - ratio*0.5)
	case entities.DefenseProjection:
		return clampUnit(1.0 - ratio*0.4)
	case entities.DefenseRationalization:
		return clampUnit(1.0 - ratio*0.6)
	case entities.DefenseDisplacement:
		return clampUnit(1.0 - ratio*0.45)
	case entities.DefenseSublimation:
		return clampUnit(1.0 - ratio*0.55)
	case entities.DefenseIntellectualize:
		return clampUnit(1.0 - ratio*0.65)
	case entities.DefenseDissociation:
		return clampUnit(1.0 - ratio*0.85)
	case entities.DefenseRegression:
		return clampUnit(1.0 - ratio*0.35)
	default:
		return clampUnit(1.0 - ratio*0.5)
	}
}

func defenseThought(mechanism entities.DefenseMechanismType) string {
	switch mechanism {
	case entities.DefenseDenial:
		return "Eso no paso. No de verdad."
	case entities.DefenseProjection:
		return "El problema no soy yo. Son ellos."
	case entities.DefenseRationalization:
		return "Tiene sentido si lo piensas bien. No hay de que preocuparse."
	case entities.DefenseDisplacement:
		return "No es con ellos con quien esta enojado. Es con todo lo demas."
	case entities.DefenseRepression:
		return "Mejor no pensar en eso ahora."
	case entities.DefenseHumor:
		return "Si no te ries, te rompes."
	case entities.DefenseSublimation:
		return "Mejor usar esa energia en algo util."
	case entities.DefenseIntellectualize:
		return "Es un fenomeno interesante, si lo analizas."
	case entities.DefenseRegression:
		return "Quiere que alguien mas se encargue."
	case entities.DefenseDissociation:
		return "Observa desde lejos, como si le pasara a otra persona."
	default:
		return "Algo dentro se cierra."
	}
}

func clampUnit(value float32) float32 {
	if value < 0 {
		return 0
	}
	if value > 1 {
		return 1
	}
	return value
}
